services:
  server:
    container_name: server
    image: node:19.05.0-alpine
    build:
      context: ./server
    depends_on:
      - database
    ports:
      - 3001:3001

    environment:
      - HOST=database
      - DBPORT=5432
      - DB=jobapp
      - USER=user
      - PASSWORD=secret
      - PORT=3001

  database:
    container_name: database
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - jobapp-db:/var/lib/postgresql/data
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=jobapp

volumes:
  jobapp-db:
