name: "Node Continuous Integration"

on:
  pull_request:
    branches: [main]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls
      - name: "Install Node"
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: "Install Dependencies"
        run: cd ./client && ls
      - name: "Run Client Tests"
        run: npm test
      - name: "Run Client Build"
        run: npm run build
      - run: ls 
      
