name: "Node Continuous Integration"

on:
  pull_request:
    branches: [main]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install Node"
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: "Install Dependencies"
        run: npm ci
      - name: "Run Tests"
        run: npm test

      - run: npm run build
