name: PostgreSQL Service

on:
  pull_request:
    branches: [main]

jobs: 
  integration-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
          
    steps:      
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install Client Dependencies
        working-directory: ~/client
        run: npm ci
      
      - name: Install Server Dependencies
        working-directory: ./server
        run: npm ci
      
      - name: Connect to PostgreSQL
        working-directory: ./server
        run: node database.js
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        
      - name: Run Client Tests
        working-directory: ./client
        run: npm run test
      
      - name: Run Server Tests
        working-directory: ./server
        run: npm run test
      
